export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BARRIER_REPORT_NOT_FOUND: "BARRIER_REPORT_NOT_FOUND",
  BARRIER_ALREADY_VERIFIED: "BARRIER_ALREADY_VERIFIED",
  VERIFY_DECISION_INVALID: "VERIFY_DECISION_INVALID",
  REFERENCE_FACILITY_NOT_FOUND: "REFERENCE_FACILITY_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
