export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BARRIER_REPORT_NOT_FOUND: "BARRIER_REPORT_NOT_FOUND",
  BARRIER_REPORT_ALREADY_VERIFIED: "BARRIER_REPORT_ALREADY_VERIFIED",
  FACILITY_NOT_FOUND: "FACILITY_NOT_FOUND"
} as const;
